exports:
  data:
    command: '"python3.7", "/app/server.py"'
    deployEnv: jenkins
    deployMode: development
    origin: http://muam.wittlesouth.com
    cookieDomain: .wittlesouth.com
    server:
      image: registry.wittlesouth.com/muam
      version: latest
      servicePort: 31311
    client:
      image: registry.wittlesouth.com/muam-client
      version: latest
    env:
      app_logging_config: "/app/server_logging.yaml"
      openapi_spec: "/app/spec/muam.yaml"
      flask_debug: 0
      secret_key: MUAMJenkinsSecretKey
      node_env: development
      app_db_name: jenkins_muam
      app_db_account: jenkins
      app_db_password: jenkinspwd
      app_db_cname: wittlesouth.com
      app_db_cport: 31999


