exports:
  data:
    command: "/app/src/server-loop"
    deployEnv: dev
    deployMode: development
    origin: http://eric.wittlesouth.local:3000
    cookieDomain: .wittlesouth.local
    apiPath: /api/v1
    host: muam.wittlesouth.local
    server:
      localPath: /mnt/hgfs/wsv/muam/server
      image: wittlesouth/api_server
      version: 1.4
#      containerPort: 8180
      servicePort: 31310
    client:
      image: localhost:32000/muam-client
      version: latest
#      containerPort: 80
