# dev-api-server.yml - Kubernetes deployment file for development API server
#
# Persistent volume specification that defines a Kubernetes persistent volume
# mapped to the server source directory. Each time you restart the server, the
# current source from your local client will be used.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: muam-test-server
  labels:
    type: server
spec:
  accessModes:
    - ReadOnlyMany
  capacity:
    storage: 5Gi
  storageClassName: server
  hostPath:
    path: /mnt/hgfs/wsv/muam/server
---
# Claim for testing server
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: muam-test-server-claim
spec:
  storageClassName: server
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
---
# Deployment specification for testing server
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: muam-test-server
spec:
  selector:
    matchLabels:
      app: muam-test-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: muam-test-server
      annotations:
        user: root
    spec:
      containers:
      - image: wittlesouth/api_server:1.3
        name: muam-test-server
        env:
        - name: MUAM_MODE
          value: "test"
        - name: ACCESS_CONTROL_ORIGIN
          value: "http://eric.wittlesouth.local:3000"
        - name: COOKIE_DOMAIN
          value: ".wittlesouth.local"
        command: ["/app/src/server-loop"]
        ports:
        - containerPort: 8180
        volumeMounts:
        - name: muam-test-server-vol
          mountPath: /app
      volumes:
      - name: muam-test-server-vol
        persistentVolumeClaim:
          claimName: muam-test-server-claim
---
# Service that exposes testing server to local network
apiVersion: v1
kind: Service
metadata:
  name: muam-test-server
spec:
  type: NodePort
  ports:
  - port: 8180
    nodePort: 31311
    targetPort: 8180
  selector:
    app: muam-test-server