apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.deployEnv }}-client
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.deployEnv }}
      task: client
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.deployEnv }}
        task: client
      annotations:
        user: root
    spec:
      containers:
      - image: {{ .Values.client.image }}:{{ .Values.client.version }}
        name: {{ .Release.Name }}-{{ .Values.deployEnv }}-client
        command: ["nginx", "-g", "daemon off;"]
        env:
        - name: MUAM_MODE
          value: {{ .Values.deployMode | quote }}
        - name: REACT_APP_API_PATH
          value: {{ .Values.apiPath | quote }}
        ports:
        - containerPort: {{ .Values.client.containerPort }}
