apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.deployEnv }}-server
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.deployEnv }}
      task: server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.deployEnv }}
        task: server
      annotations:
        user: root
    spec:
      containers:
      - image: {{ .Values.server.image }}:{{ .Values.server.version }}
        name: {{ .Release.Name }}-{{ .Values.deployEnv }}-server
        env:
        - name: MUAM_MODE
          value: {{ .Values.deployMode | quote }}
        - name: ACCESS_CONTROL_ORIGIN
          value: {{ .Values.origin | quote }}
        - name: COOKIE_DOMAIN
          value: {{ .Values.cookieDomain | quote }}
        command: ["/app/src/server-loop"]
        ports:
        - containerPort: {{ .Values.server.containerPort }}
        volumeMounts:
        - name: {{ .Release.Name }}-{{ .Values.deployEnv }}-vol
          mountPath: /app
      volumes:
      - name: {{ .Release.Name }}-{{ .Values.deployEnv }}-vol
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-{{ .Values.deployEnv }}-claim