{{ if eq .Values.deployEnv "dev" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-{{ .Values.deployEnv }}-pv
  labels:
    type: server
spec:
  accessModes:
    - ReadOnlyMany
  capacity:
    storage: 5Gi
  storageClassName: {{ .Release.Name }}-{{ .Values.deployEnv }}
  hostPath:
    path: {{ .Values.server.localPath}}
{{ end }}
