apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.deployEnv }}-server
spec:
  type: NodePort
  ports:
  - name: api
    port: {{ .Values.server.containerPort }}
    nodePort: {{ .Values.server.servicePort }}
    targetPort: {{ .Values.server.containerPort }}
  selector:
    app: {{ .Release.Name }}-{{ .Values.deployEnv }}
    task: server
