apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-{{ .Values.deployEnv }}-claim
spec:
  storageClassName: {{ .Release.Name }}-{{ .Values.deployEnv }}
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
