openapi: 3.0.0
info:
  version: 0.1.0
  title: Multimode User Authentication for Microservices
paths:
  /login:
    post:
      summary: Authenticate via Username/Password or Facebook
      tags:
        - Authentication
      description: >
        Authenticate users to the application with either username and password
        in POST data, or Facebook access_token in post data.

        Returns both an HTTP-only cookie and an authentication token
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  Users:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'
        '400':
          description: Request error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Invalid user or password
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
  /logout:
    post:
      summary: Remove authentication and exit the application
      tags:
        - Authentication
      description: |
        Ending authentication for a user requires removing a non-expiring token.
        This method will clear the JWT tokens for the application
      responses:
        '200':
          description: Successful response
        '400':
          description: User not logged in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /pw_reset:
    post:
      summary: Requests that a password reset token be sent to the given email address
      tags:
        - Authentication
      description: >
        Will request a password reset code be sent to the e-mail address
        provided in the form body.

        Will result in an e-mail being sent with an access code. The access code
        will have a 15 minute timeout.

        No new reset codes will be able to be generated for the same email
        address within the timeout window.

        Will generate a refresh token if the email address is valid, the PUT
        verb for this endpoint will require

        a valid refresh token.
      responses:
        '200':
          description: Successful response
        '400':
          description: Request error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Email address not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  description: User email address for password reset
                  minLength: 4
                  maxLength: 80
        description: Fields required to start password reset
    put:
      summary: >-
        Requests that the user's password be reset. Requires an e-mail address
        that matches the refresh token. Also requires a reset code that has not
        timed out
      tags:
        - Authentication
      description: >
        Will reset the users password to the requested value if the refresh
        token is valid, matches the email address,

        and the reset code is valid and current.
      responses:
        '200':
          description: Successful response
        '400':
          description: Request error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - reset_code
              properties:
                email:
                  type: string
                  description: User email address for password reset
                  minLength: 4
                  maxLength: 80
                password:
                  type: string
                  description: New Password
                  minLength: 8
                  maxLength: 32
                reset_code:
                  type: string
                  description: Reset code
                  minLength: 6
                  maxLength: 6
        description: Fields required to complete password reset
  /shutdown:
    post:
      description: |
        Allows for clean server shutdown.
      tags:
        - Test Utilities
      responses:
        '200':
          description: Server successfully shut down
        '404':
          description: User not authorized to shut down server
      requestBody:
        content:
          application/json:
            schema:
              type: object
              title: ShutdownKey
              properties:
                key:
                  type: string
        description: Unique application key to allow shutdown
tags:
  - name: Authentication
    description: APIs associated with application authentication
  - name: Test Utilities
    description: APIs that should only be used by test utilities
servers:
  - url: /api/v1/us
    description: Local development server
components:
  parameters:
    search_text:
      in: query
      name: search_text
      required: false
      description: String to filter search with
      schema:
        type: string
        maxLength: 40
    gid:
      in: query
      name: gid
      required: false
      description: GID (numeric group id) to filter group searches with
      schema:
        type: integer
        format: int32
  schemas:
    Error:
      type: object
      properties:
        key:
          type: string
          description: Unique identifier for error message
        text:
          type: string
          description: Default english error message
        error_code:
          type: integer
          description: Error code (equivalent to HTTP status code)
    Login:
      type: object
      properties:
        username:
          type: string
          description: Username representing identity of person requesting access
          minLength: 4
          maxLength: 12
          example: testing
        password:
          type: string
          description: Password associated with the username requesting access
          minLength: 8
          maxLength: 32
          example: Testing123!
        token:
          type: string
          description: Facebook access token
          minLength: 8
          maxLength: 120
          example: KLSDJKFJF-LKSJFLKJSDFJ
    GroupShort:
      type: object
      description: Short representation of Group
      required:
        - name
      properties:
        group_id:
          type: string
          format: uuid
          x-smoacks-model-id: true
          nullable: false
          readOnly: true
          description: Unique group identifier
          minLength: 12
          maxLength: 40
          example: b5665877-f9ee-4074-a38b-39219cde6b4d
        gid:
          type: integer
          format: int32
          nullable: true
          description: Numeric group ID (LDAP)
          example: 104
        name:
          type: string
          description: Description of the group
          minLength: 4
          maxLength: 80
          example: app-users
          x-smoacks-search-field: True
          x-smoacks-edit-unit-test: 'app-users - edited'
    Group:
      type: object
      x-smoacks-create: Group
      x-orim-test-data: True
      x-smoacks-relationships:
        memberships:
          table: Membership
          field: group
          cascade: all, delete-orphan
      description: Named collection of users
      allOf:
        - $ref: '#/components/schemas/GroupShort'
        - type: object
          properties:
            description:
              type: string
              nullable: true
              description: Long description of group
              minLength: 20
              maxLength: 3000
              example: This is a really long description of a group
            source:
              type: string
              nullable: False
              description: Source of this group (Local or LDAP)
              enum:
                - Local
                - LDAP
              readOnly: true
              example: LDAP
            record_created:
              type: string
              format: date
              description: Record creation date
              readOnly: True
              example: '1995-08-19T00:00:00.000Z'
            record_updated:
              type: string
              format: date
              description: Record update date
              readOnly: true
              example: '1995-08-19T00:00:00.001Z'
    GroupFull:
      description: Group with all attributes
      x-smoacks-update: Group
      allOf:
        - $ref: '#/components/schemas/Group'
        - type: object
          properties:
            users:
              type: array
              nullable: true
              x-smoacks-linked-object: Membership
              items:
                $ref: '#/components/schemas/UserList'
    GroupList:
      type: object
      description: List representation of Group
      properties:
        group_id:
          type: string
          nullable: false
          format: uuid
          description: Unique group identifier
          minLength: 12
          maxLength: 40
          example: b5665877-f9ee-4074-a38b-39219cde6b4d
        is_owner:
          type: boolean
          description: Indicates if the user is the owner of this group
          example: false
        is_admin:
          type: boolean
          description: Indicates if the user is an administrator of this group
          example: false
    Membership:
      x-smoacks-create: Membership
      x-orim-test-data: True
      x-smoacks-relationships:
        user:
          table: User
          field: memberships
        group:
          table: Group
          field: memberships
      type: object
      description: Group membership
      required:
        - group_id
        - user_id
      properties:
        group_id:
          type: string
          x-smoacks-model-id: true
          x-smoacks-foreign-key: Group
          format: uuid
          nullable: false
          description: Unique group identifier
          minLength: 12
          maxLength: 40
          example: b5665877-f9ee-4074-a38b-39219cde6b4d
        user_id:
          type: string
          x-smoacks-model-id: true
          x-smoacks-foreign-key: User
          format: uuid
          description: Unique user identifier
          minLength: 12
          maxLength: 40
          example: b5665877-f9ee-4074-a38b-39219cde6b67
        is_owner:
          type: boolean
          description: Indicates if the user is the owner of this group
          example: false
        is_admin:
          type: boolean
          description: Indicates if the user is an administrator of this group
          example: false
    MembershipUpdate:
      type: object
      description: Group membership
      properties:
        is_owner:
          type: boolean
          description: Indicates if the user is the owner of this group
          example: false
        is_admin:
          type: boolean
          description: Indicates if the user is an administrator of this group
          example: false
    UserShort:
      type: object
      required:
        - username
      properties:
        user_id:
          type: string
          x-smoacks-model-id: true
          format: uuid
          description: Unique user identifier
          readOnly: True
          minLength: 12
          maxLength: 40
          example: b5665877-f9ee-4074-a38b-39219cde6b67
        username:
          type: string
          description: Login user name
          minLength: 4
          maxLength: 32
          example: 'testing'
    UserCore:
      description: User
      type: object
      properties:
        email:
          type: string
          description: Email address
          pattern: ^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$
          minLength: 4
          maxLength: 80
          example: 'testing@wittlesouth.com'
        first_name:
          type: string
          description: First Name
          minLength: 2
          maxLength: 80
          example: 'Tester'
          x-smoacks-edit-unit-test: 'Tester - edited'
        full_name:
          type: string
          description: Full Name
          minLength: 5
          maxLength: 120
          example: 'Tester, Unit X'
          x-smoacks-search-field: True
        last_name:
          type: string
          description: Last Name
          minLength: 2
          maxLength: 80
          example: 'Unit'
        phone:
          type: string
          description: Phone number
          nullable: true
          minLength: 10
          maxLength: 20
          example: '+1 (919) 999-9999'
        source:
          type: string
          nullable: False
          description: Source of this user
          enum:
            - Local
            - LDAP
            - Facebook
          readOnly: true
          example: LDAP
        create_users:
          type: boolean
          default: false
          description: True if this user can create other users
          example: false
        create_groups:
          type: boolean
          default: false
          description: True if this user can create groups
          example: true
        grant_privs:
          type: boolean
          default: false
          description: True if this user can change values of create_users or create_groups for other users
          example: false
        record_created:
          type: string
          format: date
          description: Record creation date
          readOnly: True
          example: '1995-08-19T00:00:00.002Z'
        record_updated:
          type: string
          format: date
          description: Record update date
          readOnly: true
          example: '1995-08-19T00:00:00.003Z'
    User:
      x-smoacks-create: User
      x-orim-test-data: True
      x-smoacks-relationships:
        memberships:
          table: Membership
          field: user
      description: User
      allOf:
        - $ref: '#/components/schemas/UserShort'
        - $ref: '#/components/schemas/UserCore'
    UserExtended:
      x-smoacks-extended: User
      description: User with related objects list
      allOf:
        - $ref: '#/components/schemas/UserShort'
        - $ref: '#/components/schemas/UserCore'
        - type: object
          properties:
            groups:
              x-smoacks-linked-object: Membership
              nullable: true
              type: array
              items:
                $ref: '#/components/schemas/GroupList'
    UserList:
      type: object
      properties:
        user_id:
          type: string
          x-smoacks-model-id: true
          description: Unique user identifier
          format: uuid
          minLength: 12
          maxLength: 40
          example: b5665877-f9ee-4074-a38b-39219cde6b67
        is_owner:
          type: boolean
          description: Indicates if the user is the owner of this group
          example: false
        is_admin:
          type: boolean
          description: Indicates if the user is an administrator of this group
          example: false
    UserUpdate:
      x-smoacks-update: User
      description: User
      x-smoacks-test-data: False
      allOf:
        - $ref: '#/components/schemas/UserShort'
        - $ref: '#/components/schemas/UserCore'
        - type: object
          properties:
            password:
              type: string
              description: User password
              nullable: True
              minLength: 8
              maxLength: 32
              example: 'testing123'
            groups:
              type: array
              nullable: true
              x-smoacks-linked-object: Membership
              items:
                $ref: '#/components/schemas/GroupList'
