# dev-api-server.yml - Complete specification for development instance of API server
#
# Persistent volume specification that defines a Kubernetes persistent volume
# mapped to the server source directory. Each time you restart the server, the
# current source from your local client will be used.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: muam-dev-server
  labels:
    type: server
spec:
  accessModes:
    - ReadOnlyMany
  capacity:
    storage: 5Gi
  storageClassName: server
  hostPath:
    path: /Users/eric/Development/wsv/muam
---
# Claim for development server
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: muam-dev-server-claim
spec:
  storageClassName: server
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
---
# Deployment specification for development server
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: muam-dev-server
spec:
  selector:
    matchLabels:
      app: muam-dev-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: muam-dev-server
      annotations:
        user: root
    spec:
      containers:
      - image: wittlesouth/api_server:1.3
        name: muam-dev-server
        env:
        - name: NODE_ENV
          value: "development"
        command: ["/app/server/src/server-loop"]
        ports:
        - containerPort: 8081
          name: muam-dev-server
        volumeMounts:
        - name: muam-dev-server-vol
          mountPath: /app
      volumes:
      - name: muam-dev-server-vol
        persistentVolumeClaim:
          claimName: muam-dev-server-claim
---
# Service that exposes development server to local network
apiVersion: v1
kind: Service
metadata:
  name: muam-dev-server
spec:
  type: NodePort
  ports:
  - port: 8081
    nodePort: 31310
    targetPort: 8081
    name: muam-dev-server
  selector:
    app: muam-dev-server
