# Run once when testelopment DB is to be initialized
#
# Persistent Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: muam-test-db
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  storageClassName: local
  hostPath:
    path: /Users/eric/Development/wsv/muam/mysql-test
#
---
# Persistent Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: muam-test-db-claim
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
