# dev-api-server.yml - Complete specification for development instance of API server
#
# Persistent volume specification that defines a Kubernetes persistent volume
# mapped to the server source directory. Each time you restart the server, the
# current source from your local client will be used.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rftw-test-server
  labels:
    type: server
spec:
  accessModes:
    - ReadOnlyMany
  capacity:
    storage: 5Gi
  storageClassName: server
  hostPath:
    path: /Users/eric/Development/roadmapsftw/develop
---
# Claim for test server
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rftw-test-server-claim
spec:
  storageClassName: server
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
---
# Deployment specification for test server
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: rftw-test-server
spec:
  selector:
    matchLabels:
      app: rftw-test-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rftw-test-server
      annotations:
        user: root
    spec:
      containers:
      - command: ["/app/server/src/server-loop"]
        image: wittlesouth/api_server:1.2
        name: rftw-test-server
        env:
        - name: NODE_ENV
          value: "test"
        ports:
        - containerPort: 8180
          name: rftw-test-srv
        volumeMounts:
        - name: rftw-test-server-vol
          mountPath: /app
      volumes:
      - name: rftw-test-server-vol
        persistentVolumeClaim:
          claimName: rftw-test-server-claim
      restartPolicy: Always
---
# Service that exposes development server to local network
apiVersion: v1
kind: Service
metadata:
  name: rftw-test-server
spec:
  type: NodePort
  ports:
  - port: 8180
    nodePort: 31107
    targetPort: 8180
    name: rftw-test-server
  selector:
    app: rftw-test-server
